import { api } from "@/utils/api";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {

  const { data } = api.products.getAll.useQuery();

  if(!data) return <p>Loading ...</p>

  return (
    <>
      <Head>
        <title>Home - My Store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <h1>a</h1>
      </main>
    </>
  );
};

export default Home;
