import { type NextPage } from "next";
import Head from "next/head";

import { Slideshow } from "@/components/Slideshow";
import { Suspense } from "react";

import { AnimatePresence } from 'framer-motion';

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Home - My Store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <section className="px-5 my-5 space-y-5">
          <h2 className="font-bold uppercase border-b-2 border-black w-fit">Best Sellers</h2> 

          <Suspense fallback={<p>Loading...</p>}>
            <AnimatePresence>
              <Slideshow />
            </AnimatePresence>
          </Suspense>
        </section>


      </main>
    </>
  );
};

export default Home;
